name: chatops
on:
  issue_comment:
    types: [ created ]

  check_suite:
    types: [ completed ]

jobs:

  check-suite-completed:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout commit"
        uses: actions/checkout@v2

      - name: "Greet"
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.PUBLIC_REPO_ACCESS_TOKEN}}
          script: |

            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const creator = context.payload.sender.login;

            console.log('Greeting');

            let message = `
              @${creator} thanks
              `;

            await github.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: message
            });
